import { promises as fs, existsSync } from "node:fs";
import { join } from "node:path";
import { cwd } from "node:process";
import { confirm, input, password, select } from "@inquirer/prompts";
import chalk from "chalk";
import ora from "ora";

interface InitOptions {
  force?: boolean;
  silent?: boolean;
}

interface InitConfig {
  apiKey: string;
  provider: "sqlite" | "memory";
  dbPath?: string;
  useDefaults: boolean;
}

const DEFAULT_CONFIG = {
  vectorDB: {
    provider: "sqlite",
    options: {
      path: "./ragist.db",
      dimension: 768,
    },
  },
  embedding: {
    model: "text-embedding-004",
    dimension: 768,
  },
  indexing: {
    chunkSize: 1000,
    chunkOverlap: 100,
    batchSize: 100,
  },
  search: {
    defaultK: 5,
    enableRerank: true,
    rerankBoostFactor: 0.1,
    hybridKeywordWeight: 0.3,
  },
};

export async function handleInit(options: InitOptions = {}): Promise<void> {
  const { force = false, silent = false } = options;

  if (!silent) {
    console.log(chalk.bold.cyan("\n🎨 Welcome to Ragist Setup!\n"));
    console.log(
      chalk.gray(
        "This utility will help you create a .env file and ragist.config.json\n",
      ),
    );
  }

  const envPath = join(cwd(), ".env");
  const configPath = join(cwd(), "ragist.config.json");

  // Check for existing files
  const envExists = existsSync(envPath);
  const configExists = existsSync(configPath);

  if ((envExists || configExists) && !force) {
    const existingFiles = [];
    if (envExists) existingFiles.push(".env");
    if (configExists) existingFiles.push("ragist.config.json");

    console.log(
      chalk.yellow(
        `⚠️  The following files already exist: ${existingFiles.join(", ")}`,
      ),
    );

    const shouldOverwrite = await confirm({
      message: "Do you want to overwrite existing files?",
      default: false,
    });

    if (!shouldOverwrite) {
      console.log(chalk.gray("\n✖ Setup cancelled"));
      return;
    }
  }

  try {
    // Collect user input
    console.log(chalk.bold("\n📝 Configuration\n"));

    // API Key input
    console.log(
      chalk.gray(
        "Get your API key at: https://makersuite.google.com/app/apikey\n",
      ),
    );
    const apiKey = await password({
      message: "Enter your Google Generative AI API Key:",
      mask: "*",
      validate: (value) => {
        if (!value || value.trim().length === 0) {
          return "API key is required";
        }
        return true;
      },
    });

    // Vector DB configuration
    const provider = (await select({
      message: "Select vector database provider:",
      choices: [
        {
          name: "SQLite (Recommended - Local file-based storage)",
          value: "sqlite",
        },
        {
          name: "Memory (Testing only - Data lost on restart)",
          value: "memory",
        },
      ],
      default: "sqlite",
    })) as "sqlite" | "memory";

    let dbPath: string | undefined;
    if (provider === "sqlite") {
      dbPath = await input({
        message: "Database file path:",
        default: "./ragist.db",
      });
    }

    // Ask about using default configuration
    const useDefaults = await confirm({
      message: "Use default configuration for indexing and search?",
      default: true,
    });

    const config: InitConfig = {
      apiKey,
      provider,
      dbPath,
      useDefaults,
    };

    // Generate files
    console.log(chalk.bold("\n📦 Generating files...\n"));

    // Create .env file
    const envSpinner = ora("Creating .env file...").start();
    await createEnvFile(envPath, config);
    envSpinner.succeed(chalk.green("Created .env file"));

    // Create ragist.config.json
    const configSpinner = ora("Creating ragist.config.json...").start();
    await createConfigFile(configPath, config);
    configSpinner.succeed(chalk.green("Created ragist.config.json"));

    // Success message
    console.log(chalk.bold.green("\n✅ Setup complete!\n"));
    console.log(chalk.bold("Next steps:"));
    console.log(
      chalk.gray(
        "1. Run 'npx ragist index --file ./README.md' to index your first document",
      ),
    );
    console.log(
      chalk.gray("2. Run 'npx ragist query \"your search query\"' to search\n"),
    );
    console.log(
      chalk.gray(
        "For more information, visit: https://github.com/your-repo/ragist\n",
      ),
    );
  } catch (error) {
    console.error(chalk.red("\n✖ Setup failed:"), error);
    process.exit(1);
  }
}

async function createEnvFile(path: string, config: InitConfig): Promise<void> {
  const lines = [
    "# Ragist Environment Configuration",
    "# Generated by 'npx ragist --init'",
    "",
    "# Google Generative AI API Key (Required)",
    "# Get your key at: https://makersuite.google.com/app/apikey",
    `GOOGLE_GENERATIVE_AI_API_KEY=${config.apiKey}`,
    "",
    "# Vector Database Configuration (Optional)",
    `# VECTOR_DB_PROVIDER=${config.provider}`,
  ];

  if (config.provider === "sqlite" && config.dbPath) {
    lines.push(`# SQLITE_DB_PATH=${config.dbPath}`);
  }

  lines.push(
    "",
    "# Additional Configuration (Optional)",
    "# EMBEDDING_MODEL=text-embedding-004",
    "# EMBEDDING_DIMENSION=768",
    "",
  );

  await fs.writeFile(path, lines.join("\n"), "utf-8");
}

async function createConfigFile(
  path: string,
  config: InitConfig,
): Promise<void> {
  const configData = { ...DEFAULT_CONFIG };

  // Update provider and path if specified
  configData.vectorDB.provider = config.provider;
  if (config.provider === "sqlite" && config.dbPath) {
    configData.vectorDB.options.path = config.dbPath;
  }

  // If not using defaults, we could add more customization here
  // For now, we'll use the defaults as specified

  await fs.writeFile(path, JSON.stringify(configData, null, 2), "utf-8");
}
